### PR TITLE
Update Lecturer.java

### PR DESCRIPTION
**Pull request by ChristinaHenninger**
fixed that the program showed an error, when you entered a lecturer username, which doesn't exist yet.

### CODE REVIEW

**Review by jniegsch — CHANGES_REQUESTED** [review]
Why are you adding `return null` after a `return lec` statement? `return null` will never be reached. Also if it fits, we want to return that lecturer if they have the right id right?

**Comment by ChristinaHenninger** [comment]
I added the return null, because I always got an error message, if I tried to add a lecturer username which doesn't exist. how can we avoid the error message otherwise?

**Comment by jniegsch** [comment]
Could you post the error here or link to it? Then I can look at it. Mainly the return nulls should not help. I would otherwise assume that the lecturers might be null, so there should be a catch before the foreach statement. So like 
```Java
if (lecturers == null) return null;
```

**Comment by ChristinaHenninger** [comment]
I tried it again, but didn't get the error anymore... I also don't know what I did wrong...but I think we can delete this pull request then ;)

**Comment by jniegsch** [comment]
Alrighty, I'll run a few tests though to see what might have gone run, just to be sure 👍

**Pull request closed without merging**
