### PR TITLE
Update Elective.java

### PR DESCRIPTION
**Pull request by ChristinaHenninger**
Added the constructor with only the (String code) parameter
corrected the naming of a variable (line 305)

### CODE REVIEW

**Review by jniegsch — CHANGES_REQUESTED** [review]
**Required Changes**
1. Please remove the following method(s):
```Java
public Elective(String code) { ... }
```

**For More Info See** 
> v0.4.1 and v0.4.2 to see which methods have been removed from `Elective.java`

**Comment by jniegsch** [comment]
Just for info, this:
```Java
... = new Elective(courseCode);
```
has been changed to
```Java
... = Elective.getElectiveWithCourseCode(courseCode);
```

**Comment by ChristinaHenninger** [comment]
deleted constructor

**Review by jniegsch — APPROVED** [review]
Good now thanks!

**Pull request merged**
